" Basic Settings
syntax enable
filetype plugin indent on
set encoding=utf-8
set fileencoding=utf-8
set fileencodings=utf-8
set bomb
set binary
set backspace=indent,eol,start

" Editor Settings
set tabstop=2
set shiftwidth=2
set expandtab
set number
set relativenumber
set hidden
set ignorecase
set smartcase
set mouse=a
set background=dark

" UI Settings
set ruler
set cmdheight=2
set laststatus=2
set showcmd
set showmode
set showmatch
set wildmenu
set wildmode=list:longest,full
set wildignore+=*/tmp/*,*.so,*.swp,*.zip,*.pyc,*.db,*.sqlite
set colorcolumn=81
set cursorline
set list
set listchars=tab:▸\ ,trail:·,extends:>,precedes:<,nbsp:␣

" Search Settings
set hlsearch
set incsearch
set wrapscan

" Indentation
set autoindent
set smartindent
set cindent

" Folding
set foldmethod=indent
set foldlevel=99
set nofoldenable

" Performance
set lazyredraw
set ttyfast
set synmaxcol=500

" Backup and Swap
set nobackup
set nowritebackup
set noswapfile

" Splits
set splitbelow
set splitright

" Completion
set completeopt=menuone,noselect,preview
set pumheight=10

" Timeout
set timeoutlen=500
set ttimeoutlen=0

" Update time for plugins
set updatetime=300

" Sign column
set signcolumn=yes

" === Key Mappings ===

" Leader key
let mapleader = ","
let g:mapleader = ","

" Quick save
nmap <leader>w :w!<cr>

" Quick quit
nmap <leader>q :q<cr>
nmap <leader>Q :qa!<cr>

" Buffer navigation
nnoremap <leader>bn :bnext<CR>
nnoremap <leader>bp :bprevious<CR>
nnoremap <leader>bd :bd<CR>
nnoremap <leader>bf :bfirst<CR>
nnoremap <leader>bl :blast<CR>

" Window navigation
nnoremap <C-j> <C-w>j
nnoremap <C-k> <C-w>k
nnoremap <C-h> <C-w>h
nnoremap <C-l> <C-w>l

" Window resizing
nnoremap <leader>+ :resize +5<CR>
nnoremap <leader>- :resize -5<CR>
nnoremap <leader>> :vertical resize +5<CR>
nnoremap <leader>< :vertical resize -5<CR>

" Tab navigation
nnoremap <leader>tn :tabnew<CR>
nnoremap <leader>to :tabonly<CR>
nnoremap <leader>tc :tabclose<CR>
nnoremap <leader>tm :tabmove<CR>
nnoremap <leader>t<leader> :tabnext<CR>
nnoremap <leader>th :tabprevious<CR>

" Clear search highlight
nnoremap <silent> <leader><space> :nohl<CR>

" Toggle paste mode
set pastetoggle=<F2>

" Visual mode indenting
vnoremap < <gv
vnoremap > >gv

" Move lines up/down
nnoremap <A-j> :m .+1<CR>==
nnoremap <A-k> :m .-2<CR>==
vnoremap <A-j> :m '>+1<CR>gv=gv
vnoremap <A-k> :m '<-2<CR>gv=gv

" Copy to system clipboard
vnoremap <leader>y "+y
nnoremap <leader>Y "+yg_
nnoremap <leader>y "+y

" Paste from system clipboard
nnoremap <leader>p "+p
nnoremap <leader>P "+P
vnoremap <leader>p "+p
vnoremap <leader>P "+P

" === Plugin Configuration ===

" FZF configuration
nnoremap <C-p> :Files<CR>
nnoremap <leader>f :Files<CR>
nnoremap <leader>b :Buffers<CR>
nnoremap <leader>g :Rg<CR>
nnoremap <leader>t :Tags<CR>
nnoremap <leader>m :Marks<CR>
nnoremap <leader>h :History<CR>

let g:fzf_layout = { 'down': '~40%' }

" Fern file explorer
nnoremap <leader>e :Fern . -drawer -toggle<CR>
let g:fern#drawer_width = 30
let g:fern#default_hidden = 1
let g:fern#default_exclude = '\.git$'

" Airline
let g:airline_powerline_fonts = 1
let g:airline#extensions#tabline#enabled = 1
let g:airline#extensions#tabline#formatter = 'unique_tail'
let g:airline_theme = 'tokyonight'

" Fugitive
nnoremap <leader>gs :Git<CR>
nnoremap <leader>gd :Gdiffsplit<CR>
nnoremap <leader>gc :Git commit<CR>
nnoremap <leader>gb :Git blame<CR>
nnoremap <leader>gl :Git log<CR>
nnoremap <leader>gp :Git push<CR>
nnoremap <leader>gr :Git pull --rebase<CR>

" Commentary
nmap <leader>/ gcc
vmap <leader>/ gc

" Tabular
nmap <leader>a= :Tabularize /=<CR>
vmap <leader>a= :Tabularize /=<CR>
nmap <leader>a: :Tabularize /:\zs<CR>
vmap <leader>a: :Tabularize /:\zs<CR>
nmap <leader>a, :Tabularize /,<CR>
vmap <leader>a, :Tabularize /,<CR>

" Tagbar
nmap <F8> :TagbarToggle<CR>
let g:tagbar_autofocus = 1
let g:tagbar_autoclose = 1
let g:tagbar_compact = 1

" Rust
let g:rustfmt_autosave = 1
let g:rust_clip_command = 'wl-copy'

" Ruby/Rails
let g:rails_projections = {
  \ "app/controllers/*_controller.rb": {
  \   "command": "controller",
  \   "test": "spec/controllers/{}_controller_spec.rb"
  \ },
  \ "app/models/*.rb": {
  \   "command": "model",
  \   "test": "spec/models/{}_spec.rb"
  \ }}

" === Auto Commands ===

" Remove trailing whitespace on save
autocmd BufWritePre * %s/\s\+$//e

" Return to last edit position
autocmd BufReadPost *
  \ if line("'\"") > 0 && line("'\"") <= line("$") |
  \   exe "normal! g`\"" |
  \ endif

" File type specific settings
autocmd FileType python setlocal tabstop=4 shiftwidth=4
autocmd FileType go setlocal tabstop=4 shiftwidth=4 noexpandtab
autocmd FileType make setlocal noexpandtab
autocmd FileType yaml setlocal tabstop=2 shiftwidth=2
autocmd FileType json setlocal tabstop=2 shiftwidth=2
autocmd FileType markdown setlocal spell spelllang=en_gb
autocmd FileType gitcommit setlocal spell spelllang=en_gb

" Highlight yanked text
augroup highlight_yank
  autocmd!
  autocmd TextYankPost * silent! lua vim.highlight.on_yank()
augroup END

" === Custom Functions ===

" Toggle between number and relativenumber
function! ToggleNumber()
  if(&relativenumber == 1)
    set norelativenumber
    set number
  else
    set relativenumber
  endif
endfunc
nnoremap <leader>n :call ToggleNumber()<CR>

" Strip trailing whitespace
function! StripTrailingWhitespace()
  let _s=@/
  let l = line(".")
  let c = col(".")
  %s/\s\+$//e
  let @/=_s
  call cursor(l, c)
endfunction
nnoremap <leader>ss :call StripTrailingWhitespace()<CR>

" === Color Scheme ===

" Enable true color support
if has('termguicolors')
  set termguicolors
endif

" Try to load color scheme
try
  colorscheme tokyonight-night
catch
  colorscheme desert
endtry